name: PR Script
on:
  pull_request:
    types:
      - opened
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: pnpm install
        run: pnpm install

      - name: run test code
        run: pnpm test
      # 테스트 코드 실패 시 동작
      - name: if fail
        uses: actions/github-script@v7
        with:
          github-token: ${{github.token}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            console.log(github.rest.pulls)
            await github.rest.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "테스트 코드를 다시 확인해주세요.",
              event: "REQUEST_CHANGES"
            })

            await github.rest.pulls.update({
              ...context.repo,
              pull_number,
              state: 'closed'
            })
        if: failure()
